package TestInstruction_SendOnMQTypeMT_SendGeneral

import (
	TestInstruction_Standard_SendTemplateToThisDomain "github.com/jlambert68/FenixStandardTestInstructionAdmin/TestInstructionsAndTesInstructionContainersAndAllowedUsers/TestInstructions/TestInstruction_SendTemplateToThisDomain"
	"github.com/jlambert68/FenixTestInstructionsAdminShared/TypeAndStructs"
)

const (
	TestInstructionUUID_SendOnMQTypeMT_SendGeneral TypeAndStructs.OriginalElementUUIDType = TestInstruction_Standard_SendTemplateToThisDomain.TestInstructionUUID_FenixSentToUsersDomain_SendTemplateToThisDomain // "091d0f35-d74d-4634-9d3e-95a6138fb4d3"
)
