package TestInstructionContainer_SpecialSerialBaseContainer

import "github.com/jlambert68/FenixTestInstructionsAdminShared/TypeAndStructs"

const (
	TestInstructionContainerUUID_SubCustody_SpecialSerialBaseContainer TypeAndStructs.OriginalElementUUIDType = "66b85646-6caa-4830-9423-3464b2e87920"
)
